USE [master]
GO

/****** Object:  Database [Impostor]    Script Date: 04/12/2022 07:14:30 p. m. ******/
CREATE DATABASE [Impostor]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Impostor', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Impostor.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Impostor_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Impostor_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Impostor].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Impostor] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Impostor] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Impostor] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Impostor] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Impostor] SET ARITHABORT OFF 
GO

ALTER DATABASE [Impostor] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Impostor] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Impostor] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Impostor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Impostor] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Impostor] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Impostor] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Impostor] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Impostor] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Impostor] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Impostor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Impostor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Impostor] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Impostor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Impostor] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Impostor] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Impostor] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Impostor] SET RECOVERY FULL 
GO

ALTER DATABASE [Impostor] SET  MULTI_USER 
GO

ALTER DATABASE [Impostor] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Impostor] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Impostor] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Impostor] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Impostor] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Impostor] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Impostor] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Impostor] SET  READ_WRITE 
GO

